language: node_js
node_js:
- stable
branchs:
  only:
  - master
install:
- npm install
- npm install --save hexo-deployer-git
- npm install --save hexo-helper-live2d
- npm install --save live2d-widget-model-koharu
addons:
  ssh_known_hosts:
  - 134.175.240.20
before_install:
- openssl aes-256-cbc -K $encrypted_f61dd4bb83d2_key -iv $encrypted_f61dd4bb83d2_iv
  -in .travis/id_rsa_blog.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "DallenCat" #设置github用户名
- git config --global user.email 809348708@qq.com #设置github用户邮箱
# 执行的命令
after_success:
- ssh travis@134.175.240.20 -o StrictHostKeyChecking=no 'cd ~/hexoBlog-auto  && git pull  && npm run deploy'
