language: node_js
node_js:
- '8'
branchs:
  only:
  - master
env:
  - secure: "l7HTiWgr7gcEensWJURRQUBnZKF9xCdSsXc3J2IcOOWbtttMxLm5RIN1/ffTKnl4ExxN5Hvnjz6DWyNDUSe68aq8+RkYWkQYti+poJMYcYEz7js4LArGV6Z57waLWS15OiNGozbTnSOiXDPVsfU72cSR4pLElDkmVmoHoVuOt1f+JzzFr5wwGgJcqeah/XE7eTcwESkliz9gREXXNwg0DopslHix9cHGV/Mm6cOhM2UlaeFxB4Y7R9mbikV5dKaTW2aOZwF0eDsVhWSaZtucA1YKnPyqovO0wTM1zwn/iZ/da7Eq3xfrM/A57U1h3LbTqGQYHHbgtZsStn9X/f2D5pN5RiPtUerzFmP4u8IilK8CodNfAtwGlK8IhmC59wbnaklwli+Xq7AtAZYZji8gHUpt6qL1jDkZ0pm49i0x/x2dxGeMoCmX7hMVJwkkGWg2LtNeSLZSvWBppuuNUzyOKEUoaiiULm4KBpAB5HmLxeFmfZ0rgbg+bzWi1O6wqXM6odtfFHs8njzpygUZGZbVnjz0l9OEnz2mhM0jNYP0jrqWwCWf7QNk4EhaYliBVS+Ayj6/evr2MHZ6qxqVyixn7X+9wNPd+cCiV/1eZoEszpXZ6kmouZFpAj008VAh3FC0xxAbOveA7pOtaeaNehoEqVBGdbtZnBKT/CcjTG3xqwE="
addons:
  ssh_known_hosts:
  - www.daiailing.cn #受信主机，你的Linux服务器ip
after_success:
- rsync -az ./public/* travis@www.daiailing.cn:$TARGET_DIR
